---
steps:
- name: hashicorp/terraform:1.0.0
  dir: deployments/app1
  args:
  - init
- name: hashicorp/terraform:1.0.0
  dir: deployments/app1
  args:
  - '-c'
  - 'terraform apply -auto-approve -var="project_id=$PROJECT_ID"'

